# include thrift-generated code
$:.push(Dir.pwd + '/gen-rb')

require 'thrift'
require 'sodoku'

# Sodoku client was generated by running the following command:
# thrift --gen rb thrift/sodoku.thrift

begin
  port = ARGV[0] || 9888
  input_puzzle = ARGV[1] || "862300000500908040039000180108090037000207000920010604013000490080409001000005863"

  transport = Thrift::BufferedTransport.new(Thrift::Socket.new('localhost', 9888))
  protocol = Thrift::BinaryProtocol.new(transport)
  client = Sodoku::Client.new(protocol)

  transport.open()

  # Send request to solve sodoku puzzle
  result = client.solve(input_puzzle)
  puts result.inspect

  transport.close()
rescue
  puts $!
end